import img4 from './download.jpg';
function Aboutfounder() {
    return(
        <div className="aboutfounder">
            <h1 align="center">Founder</h1>
            <img src={img4} className="center" width="200px"/>
            <h3 align="center">Udyog Rattan Thiru.J.Sudhanandhen</h3>
            <p>Udyog Rattan Thiru.J.Sudhanandhen fondly known as J.S. was born on 21st September 1944 to an ideal couple M.Jaganathan and Muthulakshmi. He was the first son of his family.Thiru.J.Sudhanandhen commenced his schooling at Kalaimagal Kalvi Nilayam, Erode.He continued his schooling at Sengunthar Higher Secondary School, Erode. He did his PUC at PSG Arts and Science College, Coimbatore. Later on, he graduated B.Sc. from Presidency College, Madras.<br/><br/>
	His father M.Jaganathan was an ardent follower of Padmashri M.P.Nachimuthu Mudhaliar, an active socialist who dedicated his life for the welfare of the weavers’ society. He started the “Erode Weavers’ Cooperative Society (EROTEX)” in 1947.After his death Thiru.J.Sudhanandhen took the charge as Director of EROTEX(1967-1975). He was the President from 1975-1989 and 1991-1996(Totally 19 years). As the President of EROTEX, he increased the sales to a great extent by starting branches in many cities in Tamilnadu (Madurai, Trichy,Salem,etc.) and in other states like Andhra, Karnataka,etc. During his period as the President of EROTEX, he made a Weavers’ Colony called ‘Sudhanadhen Nagar’. It has 109 houses. At present, there is a Weavers’ Colony at Solar, Erode.<br/><br/>
	Thiru.J.Sudhanandhen had frequent opportunities to meet and work under Padmashri M.P.Nachimuthu Mudhaliar.This close association ignited the hidden passions of Thiru.J.Sudhanandhen for the welfare of the rural society. He was highly inspired by the principles of Padmashri M.P.Nachimuthu Mudhaliar. Thus at his tender age, Thiru.J.Sudhanandhen started his life as a social activist. All his strenuous efforts to uplift the society were supported by his Guru, Padmashri M.P.Nachimuthu Mudhaliar.Following the foot prints of his Guru, Padmashri M.P.Nachimuthu Mudhaliar, Thiru.J.Sudhanandhen had been the State President of “Thennindia Senguntha Mahajana Sangam”. He started so many branches state – wide. He was the responsible person for the rise of Sengunthar Community schools, hospitals and convention halls all over the state.Even at his young age, Thiru.J.Sudhanandhen was well aware of the hardships of the weavers’ society. He was always thinking and working for the welfare of the weavers. Hence, he was correctly titled “Nesavalar Nesan”. He had an ardent desire to uplift the weavers’ society. His service for the society brought him many laurels, recognitions and awards.</p>
        </div>
    );
}
export default Aboutfounder;